;;;; post-restore.lisp – re‑initialise foreign resources after a saved image is loaded
(in-package #:common-lisp-user)   ; we only need to be able to call the needed symbols
(defun %arch2-post-restore ()
  ;; Reset Dexador’s connection pool (drops stale libcurl handles)                                       
  ;; Reset Dexador's connection pool if the function exists (some Dexador versions lack it)
  (let ((sym (find-symbol "RESET-POOL" "DEXADOR")))
    (when (and sym (fboundp sym))
      (funcall sym)))
  ;; Re‑read the NVIDIA key (in case the environment changed)                                            
  (when (find-package #:harness.stage-0.nvidia)                                                          
    (setf (symbol-value (find-symbol "*NVIDIA-API-KEY*" "HARNESS.STAGE-0.NVIDIA"))                
          (uiop:getenv "NVIDIA_API_KEY")))
  ;; Restart SQLite connection and background worker thread
  (when (find-package #:harness.stage-0.db)
    (let ((init-sym (find-symbol "INIT-DB" "HARNESS.STAGE-0.DB")))
      (when (and init-sym (fboundp init-sym))
        (format t "~&[Restore Hook] Re-initializing database connection...~%")
        (funcall init-sym))))
  (when (find-package #:harness.stage-0.async-processor)
    (let ((start-sym (find-symbol "START-BACKGROUND-PROCESSOR" "HARNESS.STAGE-0.ASYNC-PROCESSOR"))
          (db-path-sym (find-symbol "*DB-PATH*" "HARNESS.STAGE-0.DB")))
      (when (and start-sym (fboundp start-sym) db-path-sym (boundp db-path-sym))
        (format t "~&[Restore Hook] Restarting background processor...~%")
        (funcall start-sym (symbol-value db-path-sym)))))
  (format t "~&[Restore Hook] Dexador reset, NVIDIA key refreshed, and context engine restarted.~%"))
    
(let ((hook (find-symbol "REGISTER-RESTORE-HOOK" "SB-EXT")))
  (when (and hook (fboundp hook))
    (funcall hook #'%arch2-post-restore)))
